### ISSUE TITLE
Lucene 7.2 support

### ISSUE THREAD

**Issue by 2beers** [DmitryKey/luke#101]
You should add support for Lucene 7.2

**Comment by DmitryKey** [comment]
thanks @2beers . There is new implementation of luke on javafx in https://github.com/DmitryKey/luke/tree/luke-javafx It is compatible with 7.2. Coming up soon.

**Comment by mocobeta** [comment]
Released Luke 7.2.0. You can download from here:
https://github.com/DmitryKey/luke/releases/tag/luke-7.2.0 (atop thinlet ver.)
https://github.com/DmitryKey/luke/releases/tag/luke-javafx-7.2.0 (atop javafx ver.)

**Comment by DmitryKey** [comment]
@mocobeta Hooray! Thanks and congratulations on luke-on-javafx release!
