### ISSUE TITLE
[JavaFX] Index path value renders incorrectly

### ISSUE THREAD

**Issue by DmitryKey** [DmitryKey/luke#106]
<img width="1100" alt="screen shot 2018-05-11 at 7 45 56" src="https://user-images.githubusercontent.com/123553/39907168-970faf12-54ef-11e8-952e-3609a06fe77d.png">

Noticed the rendering issue with Index Path: the path string is partially going under the tabbed menu.

**Comment by mocobeta** [comment]
Thank you for reporting. I fixed index path rendering. 

![luke_index_path](https://user-images.githubusercontent.com/1825333/40092294-82f13a6c-58f7-11e8-94bd-4cadde92066d.png)

And also, very long directory path is ellipted and the tooltip is displayed to show the full path.

**Comment by mocobeta** [comment]
I think it was resolved at recent releases. For cleaning up, I close this issue. You can reopen the issue anytime if it's needed.
