### ISSUE TITLE
Problems With Installation

### ISSUE THREAD

**Issue by ab-10** [DmitryKey/luke#107]
### System Specs
- java 8
- Linux Fedora 27
- Maven 3.5

### Issue

Running `mvn install -X` produces the following [output](https://gist.github.com/ab-10/3af59ad1f48f1b209a7040c0803fc309#file-gistfile1-txt) (pasted in a gist, since it's over 1K lines).

As I understand Maven cannot find the javaFX installation, I've tried pointing to it in `pom` by adding:
```
    <dependency>
        <groupId>com.oracle</groupId>
        <artifactId>javaFX</artifactId>
        <version>2.2</version>
        <scope>system</scope>
        <systemPath>C:\Program Files\Java\jre7\lib\jfxrt.jar</systemPath>
    </dependency>
```
which produced no success.

I've also tried running `luke-javafx-with-deps.jar`, using `java -jar luke-javafx-with-deps.jar`, which results in this message:
`Error: Could not find or load main class org.apache.lucene.luke.app.desktop.LukeMain`

**Comment by MaximKulikov** [comment]
Since you are using Java8, jfxrt.jar included by default, That dependency actual for java7 users. You can simply remove it, it probably should be moved to plugin section to work with java7 only, but i dont remmember how and what plugin

**Comment by mocobeta** [comment]
@ab-10 Seems you use OpenJDK.
I can compile Luke with OpenJDK 8 and separately installed OpenJFX on my Fedora box. Did you try to install OpenJFX instead of adding dependency?
I have installed OpenJFX via dnf command. 
```
# dnf install java-1.8.0-openjdk-openjfx.x86_64
```

**Comment by tfrancart** [comment]
Same behavior here, on Ubuntu. Seems like Luke requires OpenJfx :
`sudo apt install openjfx`

**Comment by mocobeta** [comment]
For cleaning up, I close this issue. You can reopen the issue anytime if it's needed.
