### ISSUE TITLE
Introduce CI tools

### ISSUE THREAD

**Issue by mocobeta** [DmitryKey/luke#110]
We have test cases in master branch, so ready to introduce CI services such as Travice CI.

**Comment by DmitryKey** [comment]
this is awesome @mocobeta 
Potentially we could publish results of builds / tests passing on the front page of the repository?

**Comment by mocobeta** [comment]
@DmitryKey yes, of course, Travice CI provides status badges it can be embedded in README file. 
https://docs.travis-ci.com/user/status-images/

**Comment by mocobeta** [comment]
@DmitryKey I added Travice CI settings for Oracle Java8/9/10. (`.travis.yml`)
Could you create a Travice CI account, and add this repository to "My repositories"?
https://travis-ci.org/

Then Travice CI runs `mvn test` on every push. 

I added build status badge in my forked repository. (See the first line of README)
https://github.com/mocobeta/luke

**Comment by DmitryKey** [comment]
@mocobeta done!
Can we make status of the builds show on Readme.md?

**Comment by DmitryKey** [comment]
Triggered a manual build on master. Getting some failures from tests: https://travis-ci.org/DmitryKey/luke/builds/409516318

**Comment by mocobeta** [comment]
@DmitryKey Thanks! Added the build status badge to README.
Some tests  occasionally fail. But after re-running the results turn to green, something wrong with lucene test framework, I've not investigated it yet.

**Comment by mocobeta** [comment]
Done 👍
