### ISSUE TITLE
Allow selection and re-ordering of columns in search result table

### ISSUE THREAD

**Issue by yossivainshtein** [DmitryKey/luke#112]
The title pretty much says it all
I use Luke 4.10.4 but I think it's not available even in the later versions.

Also in that version, changing width of the rightmost column isn't possible.

**Comment by DmitryKey** [comment]
@yossivainshtein thanks again for your contribution!

I've been testing the patch after merging to luke-thinlet. Is the intent that in the screenshot below, double clicking on columns changes the order of the rows?

![screen shot 2018-09-03 at 10 25 13](https://user-images.githubusercontent.com/123553/44981067-34b5ca00-af7a-11e8-932e-7cce23307cc4.png)

**Comment by yossivainshtein** [comment]
@DmitryKey 
No, 
I think that clicking the column headers sorts the rows according to the clicked column.
In my version, there should be another button titled "edit columns" next to the "explain" button.
Maybe it was forgotten in the PR ot was lost during the merge, I'll try to check.

**Comment by mocobeta** [comment]
#114 and #118 were merged. And, version 7.2.0.1 and 4.10.4.1 were released.
