### ISSUE TITLE
Could not find artifact net.sf.ehcache:ehcache-terracotta:jar:2.6.2 in central

### ISSUE THREAD

**Issue by carschno** [DmitryKey/luke#12]
The dependency ehcache-terracotta:2.6.2 is no longer available in Maven central. Hence, the build using Maven fails (unless you already have the artifact, I assume):

`Downloading: http://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-terracotta/2.6.2/ehcache-terracotta-2.6.2.pom`
`[WARNING] The POM for net.sf.ehcache:ehcache-terracotta:jar:2.6.2 is missing, no dependency information available`
`Downloading: http://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-terracotta/2.6.2/ehcache-terracotta-2.6.2.jar`

`[ERROR] Failed to execute goal on project luke: Could not resolve dependencies for project luke:luke:jar:4.10.1: Could not find artifact net.sf.ehcache:ehcache-terracotta:jar:2.6.2 in central (http://repo.maven.apache.org/maven2) -> [Help 1]`

However, after changing the ehcache version in pom.xml to 2.9.0 (most recent, currently), multiple errors of the following type arise:
`src/main/java/org/getopt/luke/plugins/FsDirectory.java:[21,22] package net.sf.ehcache does not exist`

**Comment by DmitryKey** [comment]
@carschno thanks for reporting. If you are familiar with the ehcache api, I will welcome your pull request.

Do you need luke for some specific Lucene version, that is not already on the releases page? https://github.com/DmitryKey/luke/releases
