### ISSUE TITLE
Unable to read Hibernate Search (Lucene 7.5) indexes.

### ISSUE THREAD

**Issue by dastamatis** [DmitryKey/luke#120]
When I try to read Lucene indexes generated on the file system, using Hibernate Search 5.10.4 (which uses Lucene 7.5.0 under the hood), I get errors that it can't open or read the index. This happens in your latest JAR release, as well as when executed from your latest source files.

**Comment by mocobeta** [comment]
@dastamatis Thanks for the reporting. Can you share the error logs when trying to read the index? We will investigate it.

**Comment by dastamatis** [comment]
~/.luke.d/luke.log only shows:
[2018-10-03 21:25:28,013] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.MenubarController registered.
[2018-10-03 21:25:28,016] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.CommitsController registered.
[2018-10-03 21:25:28,016] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.LukeController registered.
[2018-10-03 21:25:28,017] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.MenubarController registered.
[2018-10-03 21:25:28,017] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.OverviewController registered.
[2018-10-03 21:25:28,017] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.DocumentsController registered.
[2018-10-03 21:25:28,017] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.SearchController registered.
[2018-10-03 21:25:28,018] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.CommitsController registered.
[2018-10-03 21:25:28,018] DEBUG (AbstractHandler.java:34) - org.apache.lucene.luke.app.controllers.LukeController registered.

Is there some other log file?

**Comment by mocobeta** [comment]
Thanks. There is no other log file, so Luke does not emit any errors.

I will try to reproduce your problem on my PC.
Actually I have never used Hibernate Search so far, so it is helpful for me that if you provide some example Java code to create Lucene index via Hibernate Search.

**Comment by dastamatis** [comment]
I've attached the test Lucene indexes that I generated, using Hibernate Search. I assume that's what you need. BTW, I can read these indexes using Marple (a Luke alternative), but I can't read them with the original Luke nor (obviously) your Luke GUI.
[hibernate_lucene_indexes.zip](https://github.com/DmitryKey/luke/files/2444944/hibernate_lucene_indexes.zip)

**Comment by dastamatis** [comment]
sorry, this zip is probably better: 
[hibernate_lucene_indexes.zip](https://github.com/DmitryKey/luke/files/2444945/hibernate_lucene_indexes.zip)

**Comment by mocobeta** [comment]
Thanks. For the confirmation, the index's Lucene version is 7.5.0?

**Comment by dastamatis** [comment]
I believe so.
https://mvnrepository.com/artifact/org.hibernate/hibernate-search-engine/5.10.4.Final
shows org.apache.lucene » lucene-core with version 5.5.5 & updates version 7.5.0.

**Comment by mocobeta** [comment]
Thaks, I will check it tonight.

**Comment by mocobeta** [comment]
I got it. Your Hibernate Search index's Lucene version is 5.5. It is not compatible with the latest Luke, backed Lucene 7.5.0. (Lucene 7.x can read 7.x and 6.x index only.)
See:  http://hibernate.org/search/releases/5.10/

You should use compatible version of Luke with your index. Here, 5.5 or 6.x is suitable.
I can read the indexes you attached with Luke 6.6.0.

![luke660](https://user-images.githubusercontent.com/1825333/46471533-237c0980-c815-11e8-92cf-23f4742e335a.png)

You can download Luke 6.6.0 here:
https://github.com/DmitryKey/luke/releases/tag/luke-6.6.0

**Comment by dastamatis** [comment]
Thank you for looking into this, and my apologies for sending you on a goose chase! Do you guys accept financial donations? I'd be happy to donate.
All the best
Dimitri

**Comment by mocobeta** [comment]
We do not have accounts for accepting donations, but thanks for your kind offering. :)

I think this issue was solved, so I will close it.

**Comment by DmitryKey** [comment]
> Thank you for looking into this, and my apologies for sending you on a goose chase! Do you guys accept financial donations? I'd be happy to donate.
> All the best
> Dimitri

Thank you Dimitri! We will think of putting up a donate button => but beyond that really appreciate your interest and bug report.

**Comment by DmitryKey** [comment]
And update: the donate button is now up on the main page: https://github.com/DmitryKey/luke

Thanks for supporting luke! We highly value the PRs and bug reports as usual! As well as blog posts with cases for luke usage that are being collected to the luke's documentation.
