### ISSUE TITLE
Enhanced UI for CustomAnalyzer : show analysis steps

### ISSUE THREAD

**Issue by mocobeta** [DmitryKey/luke#134]
For on-the-fly inspection / debugging, it is desirable to show the more detailed step by step information in the Custom Analyzer UI.

This will be just like Solr's Analysis screen,
https://lucene.apache.org/solr/guide/7_5/analysis-screen.html

or Elasticsearch's `_analyze` API and Kibana's  Analyzer UI.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html
https://github.com/johtani/analyze-api-ui-plugin

**Comment by mocobeta** [comment]
Enhancement for one of my favorite features of revised Luke. Now I'm trapped in other issues, is there anyone who'd like to take this? :)

**Comment by johtani** [comment]
Ah, maybe me:)

**Comment by mocobeta** [comment]
@johtani welcome, and thanks for looking at this! 

Before starting this, we should take care #143.  I will work for finishing the issue 143 this weekend or next week.

**Comment by mocobeta** [comment]
For contributors: [Now Luke is a part of Apache Lucene](https://medium.com/@mocobeta/luke-become-an-apache-lucene-module-as-of-lucene-8-1-7d139c998b2). Please create an issue (if there is not exist) to [Lucene Jira](https://issues.apache.org/jira/projects/LUCENE/summary) if you want to help with this.

**Comment by mocobeta** [comment]
This was resolved on the Apache Lucene project.
https://issues.apache.org/jira/browse/LUCENE-8793
