### ISSUE TITLE
some UI problem 

### ISSUE THREAD

**Issue by LordST95** [DmitryKey/luke#144]
Hi,
I'm seeing some UI bugs in your app ...
first, open index screen is didn't show all content on first load and user should change the size of the screen. Second, Query Expression in the search tab of the app is so small that I couldn't see what I'm typing on it.
I'm guessing, the reason is my laptop's resolution but that's something that your program should handle it.

regards

**Comment by LordST95** [comment]
this is screen shot ...
![image](https://user-images.githubusercontent.com/10278253/47171441-8d1c0d80-d315-11e8-826a-509aa14d529d.png)
and for giving more info, my resolution is 192081080 and I'm using Windows10

**Comment by mocobeta** [comment]
Hi, 
what version of JDK do you use?

> my resolution is 1920*1080 and I'm using Windows10

As we noted  in [the download page](https://github.com/DmitryKey/luke/releases/tag/luke-swing-7.5.0), 
Use of JDK 9+ is highly recommended for HiDPI displays on Windows/Linux platforms (e.g. Surface Pro.)
See: http://openjdk.java.net/jeps/263

With JDK 11, I confirmed that Luke window is well displayed on my Windows 10 PC.

**Comment by LordST95** [comment]
Oh, I didn't see that part, thanks for your reply 👍 

wish you the bests
