### ISSUE TITLE
When choosing the index directory, the FileChooser dialog will not navigate to hidden directories

### ISSUE THREAD

**Issue by dbooth-boston** [DmitryKey/luke#146]
My lucene index file is in a hidden directory called ".graphdb".  When I try to select it, the FileChooser dialog does not show hidden directories, so I cannot navigate to it.

To fix it, I modified the source code of src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/OpenIndexDialogFactory.java to add one line to the browseDirectory function at line 99:

        fc.setFileHidingEnabled(false);

**Comment by mocobeta** [comment]
Thanks, I will fix it.

**Comment by mocobeta** [comment]
This fix will be included in the next release.
