### ISSUE TITLE
Having an issue reading LabKey Lucene index using Luke

### ISSUE THREAD

**Issue by chrismattmann** [DmitryKey/luke#15]
Hi, I'm getting an IndexFormatTooNewException while trying to read Lucene indexes created by http://labkey.org/ see attached file.
![labeky-lucene-luke-error](https://cloud.githubusercontent.com/assets/395887/6171717/3a0d92ec-b291-11e4-8d5f-d5b5b4f4bd9b.png)

**Comment by DmitryKey** [comment]
Hi,

Do you know what version of Lucene your indices are of?

Can you try some newer version of luke, like 4.7.0 or even the latest luke-4.10.1? Take backups of your index just in case!

List of luke releases:
https://github.com/DmitryKey/luke/releases

**Comment by chrismattmann** [comment]
Yep found it @DmitryKey thanks. Works with 4.10, I didn't see the releases section. 
![image](https://cloud.githubusercontent.com/assets/395887/6173302/a81fd830-b29b-11e4-9f24-f4c9a6d3a2f5.png)

Note that regularly double clicking on 4.10 didn't work, I had to do this (on Mac OS 10.9.4, along with JDK 1.7):
```
[mattmann-0420740:~] mattmann% java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
```
I kept receiving OOM errors:
```
[mattmann-0420740:~/Desktop] mattmann% java -jar $HOME/Downloads/luke-with-deps.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
[mattmann-0420740:~/Desktop] mattmann% java -Xms128m -Xmx256m -jar $HOME/Downloads/luke-with-deps.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
[mattmann-0420740:~/Desktop] mattmann% java -Xms128m -Xmx1024m -jar $HOME/Downloads/luke-with-deps.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

I got it to work by doing:

```
[mattmann-0420740:~/Desktop] mattmann% java -Xmx1024m -XX:MaxPermSize=256m -jar $HOME/Downloads/luke-with-deps.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

But it seems rather hackish to have to do that - any idea what up?
Thanks for maintaining Luke and keeping it going. Sincerely appreciate it it's a great project.

**Comment by DmitryKey** [comment]
@chrismattmann

ok, great you were able to figure out the index <-> luke versions.

What you see is known behaviour: luke has become a bit greedier on the perm gen size side. There is a shell script that shows, how to start luke:

https://github.com/DmitryKey/luke/blob/master/luke.sh

Thanks for your support, it is delightful to see luke is being used so widely in many projects!

**Comment by chrismattmann** [comment]
Got it, that makes sense! I will go ahead and close the issue now.
