### ISSUE TITLE
Open index

### ISSUE THREAD

**Issue by vsvetov** [DmitryKey/luke#151]
When I use the Luke with ES I need to open few indexes files. Each time I need to traverse full path to the index file before I can open it. Browse dialog does not remember the previous  open file location. It should start searching the file from the directory where the last index file was opened.
it is very annoying to traverse file directory to find the index file again and again when looking for index file.

**Comment by mocobeta** [comment]
Thinlet or JavaFX or Swing Luke remember previous opened index directory paths. Which version of Luke do you use?

**Comment by vsvetov** [comment]
Hi 
I just clone latest Luke and built 
I got this behavior 

Also I found that Luke cannot read index if I add suggestion field 
It throws exception

**Comment by mocobeta** [comment]
> I got this behavior

It is unclear to me, would you explain more details? Do you still have the problem you mentioned in the issue description?

> Also I found that Luke cannot read index if I add suggestion field
> It throws exception

Please share elasticsearch version you're using and the stack traces in log file.

**Comment by vsvetov** [comment]
I just checked luke  JavaFX branch. 
1. clone branch and install and then launch luke.sh
2. when you click on "Browse" button, search file dialog dies not remember location of the index file open before. You need to traverse to the directory again. When I need to see several ES indexes I need to traverse to the index directory many time. Much better to start from recently  open directory where last index was located.

**Comment by mocobeta** [comment]
JavaFX Luke remembers previous *successfully* opened index paths as this screen shot. 
<img width="999" alt="2018-12-07 10 54 06" src="https://user-images.githubusercontent.com/1825333/49622892-c8ca7e00-fa0e-11e8-9536-a02ec5dc4ce9.png">

If opening index fails, the path is not logged. Do you open the indexes successfully with the latest JavaFX Luke? You said "Also I found that Luke cannot read index if I add suggestion field It throws exception", the path should not be remembered because of the failure.

**Comment by vsvetov** [comment]
About complete suggestion issue I opened separate issue.
As to the open index issue the picture  you showed is not enough. Click on "Browse" button and you will find that find file browser will start search file from home directory instead of the latest  directire where last index was opened.

**Comment by mocobeta** [comment]
> Click on "Browse" button and you will find that find file browser will start search file from home directory instead of the latest directire where last index was opened.

OK, I agree that future versions of Luke support this feature. Would you create a patch for this?

**Comment by vsvetov** [comment]
Do you want that I fix the issue
or I apply provided patch ?

**Comment by mocobeta** [comment]
If you'd like to contribute to this project, patches are always welcome. Or, of course you can wait that someone (I, or anyone else) provides a patch so that we can merge it for the future release.

**Comment by mocobeta** [comment]
This was fixed in #154.

**Comment by vsvetov** [comment]
I verified the fix. The issue is closed.
Thanks
