### ISSUE TITLE
No such file or directory on MacOS.

### ISSUE THREAD

**Issue by jonnyzzz** [DmitryKey/luke#158]
```
➜  luke-swing-7.6.0 ./luke.sh
Unable to find the LUKE_PATH environnement variable.
Set LUKE_PATH to /Users/jonnyzzz/Work/luke-swing-7.6.0
./luke.sh: line 22: /Users/jonnyzzz/.luke.d/luke_out.log: No such file or directory
```

**Comment by mocobeta** [comment]
Thanks for the report. This occurs when Luke is freshly installed. (When upgrading, the log directory should already exist.)
I fixed this (#159) and created the release 7.6.0.1. https://github.com/DmitryKey/luke/releases/tag/luke-swing-7.6.0.1
