### ISSUE TITLE
Bad graphics for old Luke under macOS

### ISSUE THREAD

**Issue by marco-brandizi** [DmitryKey/luke#174]
I have to inspect an old Index (v6.x), so I'm using Luke 6.6.0. Unfortunately, its graphical aspect under under macOS is as bad as this:

![image](https://user-images.githubusercontent.com/534529/64016738-abe75500-cb1f-11e9-8d2f-96a93d7f22ef.png)

I guess you're not interested much on older versions, but I need them to check old indices, so I wonder if you know a quick fix for this (some JVM option?), or you could add support for older Lucene versions to the most recent Luke release (eg, with jars selectable from command line).

**Comment by mocobeta** [comment]
Luke 7.7.0 (implemented on Swing so it works fine on the latest JVM) should be able to open Lucene 6.x indexes. Did you try it?

**Comment by marco-brandizi** [comment]
Hi @mocobeta, it works! Many thanks.

**Comment by mocobeta** [comment]
OK, I'll close this.
