### ISSUE TITLE
How to Open Solr 8.4.0 Core Index

### ISSUE THREAD

**Issue by SomebodySysop** [DmitryKey/luke#180]
Hi.  I'm extremely new to this.  I have Solr 8.4.0 installed on Centos 7 server.  I have installed Luke v. 8.0.0.  My index is located at: /opt/solr/server/solr/test01/data/index

java version "9.0.1"

When I open Luke and select that directory, it tells me: "Cannot open path.  Not a valid lucene directory or corrupted?"

I've tried all of the options, but none of them work.  How do I proceed?

**Comment by mocobeta** [comment]
Please use Lucene bundled Luke for latest Solr index.
https://medium.com/@mocobeta/luke-become-an-apache-lucene-module-as-of-lucene-8-1-7d139c998b2

**Comment by SomebodySysop** [comment]
> You cannot open Solr 8.4.0 index via Luke 8.0.0.
> 
> Please use Lucene bundled Luke for latest Solr index.
> https://medium.com/@mocobeta/luke-become-an-apache-lucene-module-as-of-lucene-8-1-7d139c998b2

Thank you.  I am finally able to run luke successfully.

I should mention (for others who might have similar issues) that /opt/solr/server/solr/test01/data is a symbolic link to /var/solr/data/test01/data.  Apparently luke doesn't like using sym linked directories.  

And, I have to use /test01/data (not /test01/data/index).
