### ISSUE TITLE
Does not work with Lucene 8.8.1?

### ISSUE THREAD

**Issue by tuerker** [DmitryKey/luke#187]
I am trying to access an index folder created by Lucene 8.8.1 and getting the error "Not a valid lucene index or corrupted". In the log I found the following:

```
[2021-02-25T10:57:20,366]  WARN (IndexUtils.java:85) - Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/srv/bfabric/as/payara-5.2020.6/glassfish/domains/domain1/config/b-fabric-index/segments_37"))): 10 (needs to be between 7 and 9)
org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/srv/bfabric/as/payara-5.2020.6/glassfish/domains/domain1/config/b-fabric-index/segments_37"))): 10 (needs to be between 7 and 9)
```

Does this means I cannot use Luke with Lucene 8.8.x or i am doing something wrong?

If Luke cannot be used with Lucene 8.8.x which version is the latest that can be used?

**Comment by mocobeta** [comment]
As of 8.1 Luke has been bundled in Lucene itself. Please download Lucene binary package; it includes `luke` module.

**Comment by tuerker** [comment]
@mocobeta many thanks. this one works.
