### ISSUE TITLE
support for copy and paste

### ISSUE THREAD

**Issue by dpinol** [DmitryKey/luke#19]
Hi,
it would be nice if the GUI could support copy & paste, eg. to paste queries from external sources

best regards

**Comment by mocobeta** [comment]
Hi, 
Luke has some copy & paste features already,
would you please describe some more details about your request ?

We have Apache Pivot based Luke branch that is currently under development, we could be able to add new features to that.

Regards.

**Comment by dpinol** [comment]
I would like to be able to paste in any text field. Eg, the Path to the index directory, the search textbox...

I'm not able to paste neither from CTRL-V, from mouse right click nor from Menu option

thanks

**Comment by DmitryKey** [comment]
@dpinol what is your OS? CTRL-V works fine for me under ubuntu.

**Comment by mazl123321** [comment]
I am having the same issue, I am using Mac OS X 10.9.5.

Under the Search Tab "Enter search expression here:" the Text field is not support the copy and paste.

Thanks!

**Comment by DmitryKey** [comment]
@mazl123321 have you tried using command button instead of CTRL?

**Comment by DmitryKey** [comment]
Here is how thinlet handles the keyboard insert:

https://github.com/DmitryKey/luke/blob/master/src/main/java/thinlet/Thinlet.java#L3472

I'll need to check this out separately on mac later today.

**Comment by dpinol** [comment]
I'm using MacOS. Btw, I know see that CTRL-C and CTRL-V works in Mac OS. However, in Mac, it should work with cmd+C and cmd-V

thanks

**Comment by DmitryKey** [comment]
@dpinol Indeed, the command button is not really supported by luke's insert. I had a quick a look and I think I found a way how to hook it up.

what's your mac os version?

**Comment by dpinol** [comment]
Yosemite 10.10.2

**Comment by mazl123321** [comment]
@DmitryKey Thanks!! I also tried, I am using Yosemite 10.9.5, the ctrl -c and -v , ctrl-a (select all) are all working for me, I did not expect we are binding all the short cut to CTRL key, it would be very nice to use the command key though.

TiA!

**Comment by DmitryKey** [comment]
This gets fixed by #35
