### ISSUE TITLE
Reconstructing non-stored fields

### ISSUE THREAD

**Issue by kiwiclive** [DmitryKey/luke#20]
On previous luke versions, when a searched document was selected, you could click 'Reconstruct & Edit' to display the content of the index. There was a warning about the validity of the data but this feature is useful to see what is in the non-stored fields.

I have tried using luke 4.10.4 on a 4.10.3 index. Pressing the 'Reconstruct & Edit' button just seems to build the stored fields and does not display the non-stored ones. The data is in the index because it can be seen when using 'Browse by term'.

Am I not setting something up correctly ?

Thanks,
Clive

**Comment by DmitryKey** [comment]
Here is what I see for non stored, only index field:

![selection_184](https://cloud.githubusercontent.com/assets/123553/6823062/56bd4866-d2ed-11e4-8243-e6cfa695f672.png)

and the field is defined in schema like so: <field name="text" type="text_general" indexed="true" stored="false" multiValued="true"/>

Could you share the definitions of the non-stored fields you are expecting, but not seeing in the UI?

**Comment by kiwiclive** [comment]
Thanks Dmitry, I'll go do my homework and get you a unit test. I suspect in the process, I'll find the problem or at least you might see what I'm doing wrong.

**Comment by kiwiclive** [comment]
Hi Dmitry,

Here is an example that I hope shows what I mean. I am moving from lucene 3.6 to lucene 4.10.3 (Raw Lucene, not Solr). The API has moved from Field() to StringField() and TextField(). The case I am interested in is where you put and item in the index that is not-stored and not-analyzed. A bit weird I know, but we use them a lot.

Previously we would have used this:
doc.add(new Field("bbb", "2", Field.Store.NO, Field.Index.NOT_ANALYZED));

In our brave new world, I believe this has changed to:
doc.add(new StringField("aaa", "1", Field.Store.NO));

When you run the test and open the index with Luke, I can restore the legacy Field() 'bbb', but not the StringField() 'aaa'. However, the field 'aaa' did make it into the index as you can search for it and it is available in the 'Browse By Term' box. You can also see the values in the overview page. I've uploaded a luke screen, I hope it comes out. So I don't know if this is really a luke problem or a lucene version problem, but it does mean that Luke cannot display many of the non-stored, non-analyzed fields in our indexes which limits its use.

Let me know if this makes any sense !!

Regards
Clive


![luke](https://cloud.githubusercontent.com/assets/11645710/6833470/32fe2336-d325-11e4-84b3-c1c14baf67c8.png)


import com.mimecast.index5.util.JvmParamUtil;
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.standard.UAX29URLEmailAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.StringField;
import org.apache.lucene.document.TextField;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.NIOFSDirectory;
import org.junit.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

/**
 * This is a simple test to create an index to check that Luke can read all the appropriate fields.
 */
public class LukeUnitTest {

    private String indexPath = "/tmp/lukeindex";
    private IndexWriterConfig indexCfg;

    public LukeUnitTest() throws Exception {
        populate();
    }


    @Test
    public void doNothing() {

    }

    private void populate() throws Exception {
        // create an index
        Directory directory = NIOFSDirectory.open(new File(indexPath));
        indexCfg = new IndexWriterConfig(JvmParamUtil.luceneVersion(), new UAX29URLEmailAnalyzer());
        indexCfg.setOpenMode(IndexWriterConfig.OpenMode.CREATE);

        IndexWriter writer = new IndexWriter(directory, indexCfg);

        Document doc = new Document();
        doc.add(new StringField("aaa", "1", Field.Store.NO));
        doc.add(new Field("bbb", "2", Field.Store.NO, Field.Index.NOT_ANALYZED));

        // sanity check
        doc.add(new StringField("ccc", "3", Field.Store.YES));

        writer.addDocument(doc);
        writer.close();
    }
}

**Comment by DmitryKey** [comment]
@kiwiclive thank you very much for the comprehensive test and the code!
The class has this dependency: com.mimecast.index5.util.JvmParamUtil;
Can it be found in the public maven repos somewhere?

**Comment by DmitryKey** [comment]
@kiwiclive thank you very much for the comprehensive test and the code!
The class has this dependency: com.mimecast.index5.util.JvmParamUtil;
Can it be found in the public maven repos somewhere?

Or, alternatively, what version should be passed into IndexWriterConfig -- 3.6 or 4.10.3 ?

**Comment by kiwiclive** [comment]
Sorry Dmitry, I missed that one. It is 4.10.3.

I am wondering if the StringField is not an equivalent of the Field() in this case.

**Comment by DmitryKey** [comment]
@kiwiclive I have found a way to reconstruct the value of aaa field in your unit test. I need a bit of code restructuring to complete this and will share a luke binary with you once ready.

**Comment by kiwiclive** [comment]
@DmitryKey. Hey Dmitry, that is fantastic news! Thank you so much for your time and effort :-)
Clive

**Comment by DmitryKey** [comment]
@kiwiclive I have just published an alpha-release, that addresses your issue: https://github.com/DmitryKey/luke/releases/tag/luke-4.10.4-field-reconstruction

I have tested this on the index produced by your unit test. Could you pls verify and let me know, how it worked for you?

**Comment by kiwiclive** [comment]
@DmitryKey That's great. Sorry I have been on holiday but will give it a test when I get back in the office tomorrow. Thank you for the effort you have put in, I'll let you know how I fare.

**Comment by DmitryKey** [comment]
sure, no problem. If this fixes the issue, feel free to close it!

**Comment by DmitryKey** [comment]
@kiwiclive did you have a chance to try this out?

**Comment by kiwiclive** [comment]
@DmitryKey 
Apologies for not getting back sooner, I've been away. Thank you for your time. This solves my problem and I can see the fields in Luke as expected.

Really appreciate the help.
Clive

**Comment by DmitryKey** [comment]
@kiwiclive glad to hear! Thanks for verifying!
