### ISSUE TITLE
Support for Lucene 5.0

### ISSUE THREAD

**Issue by nopper** [DmitryKey/luke#21]
I am using Lucene 5.0 inside my application, but I just found out that luke only supports 4.x indices.

**Comment by DmitryKey** [comment]
We currently support up to lucene 4.10.4. There is are couple tickets in the works before we upgrade. But pull requests are always welcome!

**Comment by mocobeta** [comment]
I'm now trying to make Luke support Lucene 5.1 in my local branch.
There are many compiling errors, so I need some time to make a draft PR. I want to get ready for Lucene 5.2, but of course, more quick developers' pull requests are welcome.

**Comment by DmitryKey** [comment]
Closing this ticket, as the lucene 5.2 compatible luke has been released.
