### ISSUE TITLE
Selectively delete documents from the index

### ISSUE THREAD

**Issue by JLVeiga** [DmitryKey/luke#29]
I can't find the delete button in luke 4.10.4 running in Mac os under java1.8_40

It should appear here?

![screen shot 2015-06-19 at 14 25 12](https://cloud.githubusercontent.com/assets/6439931/8253336/0984ccdc-168f-11e5-97f8-3c8ca5fcf935.png)

Thanks in advance

**Comment by DmitryKey** [comment]
Have you seen such a feature in some earlier luke versions?

As workaround:
You could search for the document by its unique id, for example, and then use Delete All on the Search Tab. Be careful with this feature, make backups of your index!

![selection_202](https://cloud.githubusercontent.com/assets/123553/8650166/78ade006-2979-11e5-88ee-5cd09e3f11a7.png)

**Comment by mocobeta** [comment]
Lucene does not provide APIs to delete by doc id.
See: https://lucene.apache.org/core/7_5_0/core/org/apache/lucene/index/IndexWriter.html
