### ISSUE TITLE
Export all terms in a field and docids to a file

### ISSUE THREAD

**Issue by DmitryKey** [DmitryKey/luke#3]
User story:

"I would like to be able to EXTRACT all tokens for a field from the index to an external text file (along with the ID field so I can identify the relevant records) so that I can compare the tokens generated with other systems….

If that is not possible would it be possible to export the RESULTS table. For example I searched for a token and found 2589 documents contain that token.  I can page through the results display for those 2589 records but ideally I would like to extract the results table into a text file for further analysis…. Is this possible?"

**Comment by sliontc** [comment]
Any updates? I'm looking for this feature.

**Comment by mocobeta** [comment]
For proceeding this issue, I think more task clarification/specification is needed.
What the "result set" mean?

----
Here is my suggestion from reading your issue description.

> EXTRACT all tokens for a field

I suppose It may be something like Solr's terms component. If so, it is not so difficult to implement (iterate TermsEnum/PostingsEnum and dump it to file.)
Now I cannot take time for this, but I think someone with basic Lucene APIs can add such feature to Document tab. Anyone interested?

**Comment by mocobeta** [comment]
For contributors: [Now Luke is a part of Apache Lucene](https://medium.com/@mocobeta/luke-become-an-apache-lucene-module-as-of-lucene-8-1-7d139c998b2). Please create an issue (if there is not exist) to [Lucene Jira](https://issues.apache.org/jira/projects/LUCENE/summary) if you want to help with this.

**Comment by mocobeta** [comment]
I migrated this issue to Lucene Jira: https://issues.apache.org/jira/browse/LUCENE-8764

**Comment by mocobeta** [comment]
This was resolved on the Apache Lucene project. (LUCENE-8764)
