### ISSUE TITLE
200 stars

### ISSUE THREAD

**Issue by DmitryKey** [DmitryKey/luke#31]
number 200 gets to file an issue to be solved with top priority as long, as it is related to luke and solvable :)

**Comment by DmitryKey** [comment]
prize goes to @gr0

**Comment by gr0** [comment]
Oh man, I'll have to think about it ;)

**Comment by DmitryKey** [comment]
are you using luke? Did you know there is an apache pivot based one? https://github.com/DmitryKey/luke/tree/pivot-luke

**Comment by gr0** [comment]
Finally back at home :) I'm using Luke from time to time, depending on the needs and yes, I was aware about the pivot based one.

**Comment by DmitryKey** [comment]
@gr0 cool, glad you are using luke. Do file a ticket once you get a feature idea or find a bug ;)
