### ISSUE TITLE
Tools -> Cleanup Index Dir -- NoSuchFileException

### ISSUE THREAD

**Issue by lambdaupb** [DmitryKey/luke#39]
I get an error when I call "Tools -> Cleanup Index Dir".

Error: java.nio.file.NoSuchFileException: 
[...]/index_new/idx/idx

While the index dir itself is just index_new, I think idx is appended twice maybe ?

Not sure if it is related, but I encountered it with a build of the pull request #27

**Comment by lambdaupb** [comment]
My Fault :/

The actual index dir was "index_new/idx" but it normally opened when I just selected "index_new"

When opening the proper path, Cleanup Index Dir works as expected.

**Comment by DmitryKey** [comment]
good, thanks. In luke there is some extra logic for handling cases, like opening index dirs from data/ in solr. This of course could be improved to search for directories with segments. Patches welcome :)
