### ISSUE TITLE
Maven shade plugin build errors

### ISSUE THREAD

**Issue by kamaldeep-ebay** [DmitryKey/luke#40]
Maven shade plugins gives some errors while building 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.3:shade (default) on project luke: Error creating shaded jar: error in opening zip file /Users/<user>/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar -> [Help 1]

We can comment out the maven-shade-plugin from pom to solve this.

**Comment by DmitryKey** [comment]
Hey,

why does it say /Users//.m2 ? Have you scratched the username in your report or is there an issue with your setup? What maven version are you using?
