### ISSUE TITLE
How exactly we do we run this Luke? Build failures..

### ISSUE THREAD

**Issue by robertmarkbram** [DmitryKey/luke#42]
Hi, 

I downloaded https://github.com/DmitryKey/luke/archive/master.zip. `luke.bat` and `luke.sh` and `java -XX:MaxPermSize=512m -jar luke-with-deps.jar` all failed out of the box, presumably because the project wasn't built, so I tried to build.

This is what I get when trying to build. This is the second run - the first run is where it downloaded all the dependencies it could find.

    D:\Users\rbram\myApps\Luke>mvn test
    [INFO] Scanning for projects...
    [WARNING]
    [WARNING] Some problems were encountered while building the effective model for luke:luke:jar:5.3.0
    [WARNING] 'version' contains an expression but should be a constant. @ luke:luke:${lucene.version}, D:\Users\rbram\myApps\Luke\pom.xml, line 9, column 14
    [WARNING]
    [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
    [WARNING]
    [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
    [WARNING]
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building luke 5.3.0
    [INFO] ------------------------------------------------------------------------
    [WARNING] The POM for org.restlet.jee:org.restlet:jar:2.3.0 is missing, no dependency information available
    [WARNING] The POM for org.restlet.jee:org.restlet.ext.servlet:jar:2.3.0 is missing, no dependency information available
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1.949 s
    [INFO] Finished at: 2015-11-16T11:26:05+11:00
    [INFO] Final Memory: 12M/244M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project luke: Could not resolve dependencies for project luke:luke:jar:5.3.0: The following artifacts could not be resolved: org.restlet.jee:org.restlet:jar:2.3.0, org.restlet.jee:org.restlet.ext.servlet:jar:2.3.0: Failure to find org.restlet.jee:org.restlet:jar:2.3.0 in http://10.6.9.14:8081/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I tried to get around this by downloading the dependencies directly into my local maven repo (after removing the *.lastupdated files) from:
http://repo.spring.io/libs-release-remote/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.jar
http://repo.spring.io/libs-release-remote/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
http://repo.spring.io/libs-release-remote/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.jar
http://repo.spring.io/libs-release-remote/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
http://repo.spring.io/libs-release-remote/org/restlet/jee/org.restlet.parent/2.3.0/org.restlet.parent-2.3.0.pom

And then I tried again:
    
    D:\Users\rbram\myApps\Luke>mvn test
    [INFO] Scanning for projects...
    [WARNING]
    [WARNING] Some problems were encountered while building the effective model for luke:luke:jar:5.3.0
    [WARNING] 'version' contains an expression but should be a constant. @ luke:luke:${lucene.version}, D:\Users\rbram\myApps\Luke\pom.xml, line 9, column 14
    [WARNING]
    [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
    [WARNING]
    [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
    [WARNING]
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building luke 5.3.0
    [INFO] ------------------------------------------------------------------------
    [INFO]
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ luke ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 54 resources
    [INFO]
    [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ luke ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 53 source files to D:\Users\rbram\myApps\Luke\target\classes
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2.955 s
    [INFO] Finished at: 2015-11-16T11:41:14+11:00
    [INFO] Final Memory: 14M/244M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project luke: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    
Feel free to call me a n00b.. any ideas on how I can get this to work?

Rob
:)

**Comment by mocobeta** [comment]
Hi,

You can get binary luke module from here. Please download luke-5.3.0-luke-release.zip, unzip it and just run luke.sh.
https://github.com/DmitryKey/luke/releases

> To see the full stack trace of the errors, re-run Maven with the -e switch.
If you need to build on your own, can you share stack traces in logs?

**Comment by robertmarkbram** [comment]
Thanks for that.. got the release and used it. Then I got `This version of Lucene only supports indexes created with release 4.0 and later.` and it seems we are using Lucene 3.6.2. Oh well. :)
