### ISSUE TITLE
upgrade to 5.4

### ISSUE THREAD

**Issue by DmitryKey** [DmitryKey/luke#46]

**Comment by lukhnos** [comment]
I made a PR that upgrades to 5.4.0, if anyone is interested: https://github.com/DmitryKey/luke/pull/47. Thanks!

**Comment by mohsa** [comment]
Hi
Hoe to upgrade luke 5.3 so that it can work with lucene 5.4...?

Are you going to release luke 5.4 soon?

**Comment by DmitryKey** [comment]
@mohsa currently master supports lucene 5.4. I'm planning to release it soon, for now you could compile it yourself. Let me know if any issue pops up.
