### ISSUE TITLE
Support for old index versions

### ISSUE THREAD

**Issue by alexanderpanchenko** [DmitryKey/luke#58]
Hello, 

Is there any version of Luke that can open Lucene 4.4.0 index files? 
The latest version seems to be incompatible with these.

**Comment by mocobeta** [comment]
Hi, the latest Lucene (6.0.0) does no longer support Lucene 4.x indexes, so the latest Luke (including Lucene 6.0.0) also does not.
You need Luke version that's compatible with your lucene index.
I've not tested yet myself, but Luke 5.x should work with Lucene 4.x.  Could you try that?

**Comment by alexanderpanchenko** [comment]
thanks, I will try this. generally, it think it is nice to have support of old index versions.
