### ISSUE TITLE
Upgrade to Lucene 6.1.0

### ISSUE THREAD

**Issue by metacube-shivang** [DmitryKey/luke#59]
Lucene's new version 6.1.0 has been available since 2016-06-17. Update to that.

**Comment by mocobeta** [comment]
OK, of course we know that next release is needed. I cannot take time to update right now, is there anyone who want to work for supporting Lucene 6.1.0?

**Comment by DmitryKey** [comment]
@metacube-shivang @mocobeta did a trivial pom upgrade & release. Pls test as you have time: https://github.com/DmitryKey/luke/releases/tag/luke-6.1.0

**Comment by mocobeta** [comment]
@DmitryKey Thank you for release! I'll check it soon.

**Comment by DmitryKey** [comment]
thanks @mocobeta !

**Comment by metacube-shivang** [comment]
@DmitryKey I did some very basic testing (viewing documents, searching) on an index created with the 6.1.0 API, and it worked for me.

**Comment by DmitryKey** [comment]
@metacube-shivang thanks. Closing this ticket for now.
