### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by DmitryKey** [DmitryKey/luke#65]

**Comment by fhopf** [comment]
I started pulling some of the Lucene-related code out of the Luke class to improve testability of those parts.

**Comment by DmitryKey** [comment]
@fhopf sounds really good, anything that improves code readability is fantastic

**Comment by mocobeta** [comment]
I think this issue was resolved on JavaFX / Swing ver. Luke (it has unit tests atop the lucene test framework.)

It should be noted - here is the related issue to be resolved: #111
