### ISSUE TITLE
pivot-luke-5.5.0 - Batch file pointing to wrong file

### ISSUE THREAD

**Issue by javahippie** [DmitryKey/luke#75]
I was using pivot-luke-5.5.0. The batch file of the release is pointing to .\target\luke-with-deps.jar, but the jar files name is pivot-luke-with-deps.jar

**Comment by mocobeta** [comment]
Thanks for the report. I will fix it and make release pivot-luke for lucene 6.

**Comment by DmitryKey** [comment]
@mocobeta did you have a chance to complete this?

**Comment by mocobeta** [comment]
@DmitryKey Sure, I was busy these days for my job change, I'll resume this soon! ;)

**Comment by DmitryKey** [comment]
@mocobeta Thanks! Sounds great, I hope your new gig is exciting place.
I'm chronically busy as well, just returned to #68 :)

**Comment by mocobeta** [comment]
Merged!
