### ISSUE TITLE
upgrading solr 4.3.1 to 4.10.3

### ISSUE THREAD

**Issue by singhimayank** [DmitryKey/luke#78]
An SPI class of type org.apache.lucene.codecs.DocValuesFormat with name 'Disk' does not exist.
Seeing this error after upgrading the war file from solr-4.3.1 to solr-4.10.3 after removing the field docValuesFormat from schema.xml since it is not supported after 4.8 version

**Comment by DmitryKey** [comment]
Hello! Did you reindex after removing the field?

**Comment by singhimayank** [comment]
Hey, 
I did not reindex my data, was hoping to avoid it.
Is there anyway to upgrade from solr-4.3.1 to solr-4.10.3 without reindexing?

**Comment by DmitryKey** [comment]
Hi,
There is IndexUpgrader lucene tool supplied with solr. You could try that. Be sure to take backups just in case.
https://cwiki.apache.org/confluence/display/solr/IndexUpgrader+Tool
