### ISSUE TITLE
pivot-luke-5.5.0 sh file edit

### ISSUE THREAD

**Issue by SahilAgarwal321** [DmitryKey/luke#82]
luke.sh file -

```
if [[ -d `echo $LUKE_PATH` ]]; then
  java -XX:MaxPermSize=512m -jar $LUKE_PATH/target/luke-with-deps.jar
else
  echo "Unable to find the LUKE_PATH environnement variable..."
  echo "Assuming you're running from the root folder of luke..."
  java -XX:MaxPermSize=512m -jar target/pivot-luke-with-deps.jar
fi

```
luke.bat file -

`java -XX:MaxPermSize=512m -jar .\target\luke-with-deps.jar
`

The jar file name in the target folder is pivot-luke-with-deps.jar so running the files shows **Error: Unable to access jarfile target/luke-with-deps.jar**

**Comment by DmitryKey** [comment]
@SahilAgarwal321 thanks for reporting! luke.bat file issue was taken care in https://github.com/DmitryKey/luke/issues/75

I'll fix the shell script.

**Comment by DmitryKey** [comment]
@SahilAgarwal321 actually, after checking: shell script is fixed too, but not released yet. Could you use the bat and sh script versions from the branch https://github.com/DmitryKey/luke/tree/pivot-luke in the meantime?

**Comment by SahilAgarwal321** [comment]
Just wanted to get this in your attention. I edited the scripts to point to the jar file.

**Comment by DmitryKey** [comment]
@SahilAgarwal321 thanks! Next release of pivot-luke should fix this.

**Comment by pangxiaoming** [comment]
outstanding！=-=
