### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tech-begemot** [DmitryKey/luke#88]
Luke cannot open the Lucene index and throws java.lang.ArrayIndexOutOfBoundsException:
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.getopt.luke.Luke.initFieldList(Luke.java:1229)
	at org.getopt.luke.Luke.access$600(Luke.java:86)
	at org.getopt.luke.Luke$3.run(Luke.java:1162)

I use   Elasticsearch 5.4.0, based on Lucene 6.5.0.
While Kibana show all results well. Elasticsearch-head also open the index and can browse all documents and its fields. 
It looks like a bug

**Comment by mocobeta** [comment]
@tech-begemot which version Luke do you use? And, can you provide the mapping of Elasticsearch?

**Comment by tech-begemot** [comment]
Hi Tomoko

Thanks for response.
I use 6.5.0 ( 2017-05-09)

I found the issue in search_analyzer

{
  "_k_en_as_keyword": {
    "match": "*_s_en",
    "mapping": {
      "type": "text",
      "analyzer": "custom_analyzer_keyword",
      "search_analyzer": "custom_analyzer_keyword"
    }
  }
},


Note, "search_analyzer" and "analyzer" use the same
"custom_analyzer_keyword".
Once mapping is loaded search_analyzer is not shown in Kibana _mapping for
any *_s_en fields. And all works fine except Luke which throws exception.
If I remove "search_analyzer": "custom_analyzer_keyword" from dynamic
template Like works fine.

Regards
Vlad

**Comment by mocobeta** [comment]
The issue was created a year ago..., sorry I had not enough time for digging this.
It was about Thinlet Luke, this has been replaced JavaFX / Swing Luke. I hope the problem was solved in recent releases.

For cleaning up old issues, I will close this issue. You can reopen it anytime if it's needed.
