### ISSUE TITLE
web interface of luke

### ISSUE THREAD

**Issue by ghaseminya** [DmitryKey/luke#92]
Hi @DmitryKey 
Is there a web interface of luke?
Thanks

**Comment by DmitryKey** [comment]
hi @ghaseminya !

There is some work done in the web interface direction here: https://github.com/flaxsearch/marple
Also some work has been started to support reading remote index: https://github.com/DmitryKey/luke/tree/luke-remoteindex
If you are more into command line luke, then check this out: https://github.com/javasoze/clue

**Comment by ghaseminya** [comment]
thanks,
I wanted to write a web interface on luke, but with your replay i think marple is good and develop it for some new task.

**Comment by DmitryKey** [comment]
sounds good!
