### ISSUE TITLE
cannot use querypaser with backslash

### ISSUE THREAD

**Issue by neal1991** [DmitryKey/luke#95]
I want to search `:1234567890` with a regular expression `/\\:[0-9]{10}/`. But it does not work. It seem the regular expression in QueryParse does not work correctly with backslash. Or is there a correct way to build an appropriate regular expression.

**Comment by mocobeta** [comment]
@neal1991 
Double backslash means backslash `\` itself. 
Did you try `/\:[0-9]{10}/`?

**Comment by neal1991** [comment]
@mocobeta I have tried, there is no result. And singnle `\` is not allowed in java.

**Comment by mocobeta** [comment]
@neal1991 Do you use Luke search tab? I can search `:1234567890` by `/\:[0-9]{10}/` from Luke's "Search" tab.

**Comment by neal1991** [comment]
@mocobeta yeah. The content is :
62228123
340223199101057212
1234567890
：1234567890
:1234567890

**Comment by neal1991** [comment]
@mocobeta `:1234567890` works. But `/\:[0-9]{10}/` will not work.

**Comment by mocobeta** [comment]
I've indexed `:123456789` to `cat` field and search by query `cat:/\:[0-9]{10}/`. Here is screen shot.
Just seems it works fine.

![screenshot from 2017-10-20 16-05-21](https://user-images.githubusercontent.com/1825333/31809153-4e2c7f24-b5b1-11e7-941f-9506401e4e45.png)


Can you describe more details?

**Comment by neal1991** [comment]
@mocobeta weired. If you have contacted a string in the front, for example: regular expression `cat/\:[0-9]{10}` works for `cat:1234567890'. But regular expression `/\:[0-9]{10}/` does not work for `:1234567890`.

**Comment by neal1991** [comment]
![image](https://user-images.githubusercontent.com/12164075/31809492-9006e71a-b5aa-11e7-9a98-ac1f68f49bf1.png)

**Comment by neal1991** [comment]
![image](https://user-images.githubusercontent.com/12164075/31809501-9ef83404-b5aa-11e7-84c2-77b1cdd07d07.png)

**Comment by mocobeta** [comment]
`cat:/\:[0-9]{10}/` means, search `cat` field by query `/\:[0-9]{10}/`.
What field do you want to search? Try `<field_name>:/\:[0-9]{10}/` after replacing <field_name> to field name you want to search.

**Comment by neal1991** [comment]
Sorry, I misunderstood your meaning. I thought `cat` is a string. In my case I want to search the field `content`. But it still does not work
![image](https://user-images.githubusercontent.com/12164075/31809877-2b67f4b4-b5ac-11e7-96ab-1f599dd0f8ef.png)

**Comment by neal1991** [comment]
I have found that if I add a feild `:1234567890` manually in luke. It can be searched. But in the content I have indexed, the content does contains the string `:1234567890`.

**Comment by mocobeta** [comment]
I have not yet correctly understood your problem, but it may not be about QueryParser but analyzing...

**Comment by neal1991** [comment]
So let me illustrate the problem in detail. I have a txt file, the content of it:
```
340223199101057212
1234567890 :1234567890
：1234567890
cat:1234567890
```
I have a program has indexed the file content with the fileld `content`. And I want to search `:1234567890` with the regular expression `/\:[0-9]{10}/`. But it searches no result.

**Comment by mocobeta** [comment]
What analyzer do you use at indexing? The term `:1234567890` is surely indexed in `content` field?

**Comment by neal1991** [comment]
standanalyzer. And you can tried to add the above text to a field, I believe it will not work for you either.

**Comment by mocobeta** [comment]
StandardAnalyzer (using StandardTokenizer internally, that split strings by `:`) removes `:`. 
If you want search `:`, you cannot use StandardAnalyzer.
e.g., StandardAnalyzer may tokenize `1234567890 :1234567890` to `1234567890` and `1234567890`.

**Comment by neal1991** [comment]
@mocobeta Thanks for your patience. You do help me. And I want to figure out a way to add these characters into StandardAnalyzer. Or build a custom Analyzer.

**Comment by mocobeta** [comment]
@neal1991 I do not know good way to modify the behavior of StandardAnalyzer from API, you may want to build a custom Analyzer. Good Luck!

**Comment by mocobeta** [comment]
For cleaning up, I close this issue.
