### ISSUE TITLE
Luke atop JavaFX

### ISSUE THREAD

**Issue by mocobeta** [DmitryKey/luke#97]
This issue is about the one of the goal of this project:

> 1. To port the thinlet UI to an ASL compliant license framework so that it can be contributed back to Apache Lucene. 

Although there is a branch atop Apache Pivot, I think it would be reasonable to use JavaFX as the UI framework for the future maintenance.

I've started to re-implement Luke atop JavaFX from scratch with modern Java syntax and APIs.
The latest codes are here: https://github.com/DmitryKey/luke/tree/luke-javafx

- Licensed under ASLv2.
- Almost all major luke functionalities were ported. (browsing index, searching docs, optimizing/checking  index, etc.)
- It works with Lucene 7.1 and supports recent Lucene features (DocValues, PointValues, etc.)
- Some outdated or not-maintained codes are discarded and not re-implemented yet.

Please try the branch and your feedback is welcome! 
Now the repository earns 800+ stargazers, I would like to accelerate our efforts to contribute back to Lucene. ;)

**Comment by DmitryKey** [comment]
@mocobeta this is awesome, thanks for your commitment. I will give it a try and let you know!

**Comment by DmitryKey** [comment]
@mocobeta tested on Finnish wikipedia index (over 1 million docs). First off, the UI looks awesome, great work!

On overview tab: if field does not have terms, we could may be show some message box about that. Currently UI shows previous field data, and console has exception.

![screen shot 2017-12-18 at 15 38 38](https://user-images.githubusercontent.com/123553/34108722-d5ff8c62-e409-11e7-9292-b590359bef15.png)

**Comment by DmitryKey** [comment]
correction: status message in the lower part of the app shows: "Top terms not available". May be that is good enough.

**Comment by DmitryKey** [comment]
btw, new Logs tab is very handy

**Comment by DmitryKey** [comment]
@mocobeta I gave it a bit more testing and works great so far. My current project requires usage of luke for versions 5 through 7. If all goes fine we could make this branch the master and move current master into a branch with thinlet suffix.

**Comment by mocobeta** [comment]
@DmitryKey Thanks for testing, I found WebView (Webkit) is not working with OpenJDK + OpenJFX registered in Fedora's DNF repository. A few dialogs using WebView are needed to rewrite with other components.
With Oracle Java, it works fine...

**Comment by mocobeta** [comment]
Compiling and Running is OK with OpenJDK (OpenJFX) !

**Comment by DmitryKey** [comment]
Very good @mocobeta ! Do you have a chance of testing this out on a windows box?

**Comment by mocobeta** [comment]
@DmitryKey Seems it works fine with my Windows10 PC. 
And I've done some additional tests with JDK 9.0.1. All features are okay with it.

**Comment by mocobeta** [comment]
Update: The branch now supports Lucene 7.2.0.

**Comment by DmitryKey** [comment]
@mocobeta looks very good, thanks for additional testing on Windows 10. And for upgrading to 7.2.0!

At this point, I believe, we are good to switch branches around. Would you like to do this?

**Comment by DmitryKey** [comment]
@mocobeta I added the luke icon to the app, could please you check it out on some OS other than mac?

**Comment by mocobeta** [comment]
@DmitryKey I replaced Collector tab with Sort & result paging (actually, those uses Collectors internally.) I guess exposing sort & result paging would be more handy than exposing 
low-level Collector APIs. I have never used Collectors tab, but sure, it may be possible to implement if it's needed. You have used Collectors tab?

**Comment by DmitryKey** [comment]
@mocobeta actually never :) so I propose to wait for external feedback on this. Otherwise +1 for the change you did.

**Comment by DmitryKey** [comment]
Wrote a blog about luke on javafx: https://dmitrykan.blogspot.fi/2018/01/new-luke-on-javafx.html

**Comment by mocobeta** [comment]
I did code refactoring, added ALv2 copyright notice and upgraded Lucene version to 7.3.0.
Seems ready to move this branch to master and prepare the next release!

**Comment by DmitryKey** [comment]
@mocobeta godspeed!

**Comment by mocobeta** [comment]
@DmitryKey 
Moved this branch to master and released as Luke 7.3.1 !
Old master (Thinlet luke) has been saved to `luke-thinlet` branch.
Now master branch is running JavaFX version, I will close the issue

**Comment by DmitryKey** [comment]
thanks @mocobeta !
